### ISSUE TITLE
Zip Loading

### ISSUE THREAD

**Issue by RobLoach** [kivutar/go-playthemall#3]
Allow loading through compressed files.

[PhysFS](https://icculus.org/physfs/) would allow mounting zip files, and then loading them without having to unzip.

Go-PhysicsFS could use an update...
https://github.com/DeedleFake/Go-PhysicsFS/

**Comment by kivutar** [comment]
Would PhysFS work with cores that need_fullpath?

**Comment by RobLoach** [comment]
PhysFS does extraction. You set a write directory, and then copy files into the write directory. It figures out extraction methods and such for you.

For needs_fullpath, we could use that method with the tmp directory of it's in an archive.

Which cores opt for needs_fullpath? ScummVM, Lutro, etc?

**Comment by kivutar** [comment]
> PhysFS does extraction. You set a write directory, and then copy files into the write directory. It figures out extraction methods and such for you.

Like an abstraction layer over zip, 7zip, tar?

I was thinking it was more like a virtual filesystem..

> Which cores opt for needs_fullpath? ScummVM, Lutro, etc?

Some traditional emulators also need_fullpath
